### ISSUE TITLE
Homework 3

### ISSUE THREAD

**Issue by pistriak** [J-alexandr/com.geekhub.homework#2]
1. You should have some king of product type; 
2. You should be able to calculate the inventory value for a given category; 
For example: I want to know the inventory value for ProductType.PHONE
and I'd call inventory.getInventoryValue(ProductType.PHONE)

**Comment by J-alexandr** [comment]
Added enum ProductCategory.
Added new field to the Product class. Now all products belong to some category.
Added new method Inventory#getCategoryValue(ProductCategory) to calculate some category value.
MainClass refactoring: clean readCommands method, rename some methods, etc.

**Comment by pistriak** [comment]
1. Don't use more than 1 blank lines
```
    public Product(ProductCategory productCategory, String name, int price) {
        this.productCategory = productCategory;
        this.name = name;
        this.price = price;
    }


    public ProductCategory getProductCategory() { return productCategory; }

    public int getPrice() {
        return price;
    }
```
2. It's hard to read and maintain such code:
```
 Map.Entry pair = (Map.Entry) iterator.next();
            if (productName.toLowerCase().equals(((Product) pair.getKey()).getName().toLowerCase()))
                summaryValue += ((Product) pair.getKey()).getPrice() * Integer.parseInt(pair.getValue().toString());
```

```
        Iterator iterator = store.entrySet().iterator();
        while (iterator.hasNext()) {
            Map.Entry pair = (Map.Entry) iterator.next();
            if (productName.toLowerCase().equals(((Product) pair.getKey()).getName().toLowerCase())) {
                iterator.remove();
                success = true;
            }
        }
```

Try to simplify the code. 

You can create a multimap Map<ProductType, List<Product>> and your code will be  a lot better;
